# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target ‘PlacesApp’ do


pod 'Alamofire'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'KeyboardDismisser'
pod 'ScrollTo'
pod 'ActionSheetPicker-3.0'
pod 'TTTAttributedLabel', '~> 2.0'
pod 'AlamofireImage', '~> 3.3'

pod 'Bagel', :git => 'https://github.com/yagiz/Bagel.git', :branch => 'pre'

end
